
[font]
size = 15

[scrolling]
history = 10_000

[window]
opacity = 0.7
blur=true
  [window.dimensions]
  columns = 110
  lines = 40

[general]
import = [ "~/.config/alacritty/themes/themes/gruvbox_light.toml" ]

